/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as TrackRegistrationIndexRouteImport } from './routes/track-registration/index'
import { Route as VisitorRegistrationIndexRouteImport } from './routes/visitor-registration/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as VisitorRegistrationSuccessIndexRouteImport } from './routes/visitor-registration/success/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRegistrationIndexRoute = TrackRegistrationIndexRouteImport.update({
  id: '/track-registration/',
  path: '/track-registration/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitorRegistrationIndexRoute =
  VisitorRegistrationIndexRouteImport.update({
    id: '/visitor-registration/',
    path: '/visitor-registration/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/admin/dashboard/',
  path: '/admin/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitorRegistrationSuccessIndexRoute =
  VisitorRegistrationSuccessIndexRouteImport.update({
    id: '/visitor-registration/success/',
    path: '/visitor-registration/success/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/track-registration/': typeof TrackRegistrationIndexRoute
  '/visitor-registration/': typeof VisitorRegistrationIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/visitor-registration/success/': typeof VisitorRegistrationSuccessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/track-registration': typeof TrackRegistrationIndexRoute
  '/visitor-registration': typeof VisitorRegistrationIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/visitor-registration/success': typeof VisitorRegistrationSuccessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/track-registration/': typeof TrackRegistrationIndexRoute
  '/visitor-registration/': typeof VisitorRegistrationIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/visitor-registration/success/': typeof VisitorRegistrationSuccessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/login'
    | '/track-registration/'
    | '/visitor-registration/'
    | '/admin/dashboard/'
    | '/visitor-registration/success/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/track-registration'
    | '/visitor-registration'
    | '/admin/dashboard'
    | '/visitor-registration/success'
  id:
    | '__root__'
    | '/'
    | '/admin/login'
    | '/track-registration/'
    | '/visitor-registration/'
    | '/admin/dashboard/'
    | '/visitor-registration/success/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  TrackRegistrationIndexRoute: typeof TrackRegistrationIndexRoute
  VisitorRegistrationIndexRoute: typeof VisitorRegistrationIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  VisitorRegistrationSuccessIndexRoute: typeof VisitorRegistrationSuccessIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-registration/': {
      id: '/track-registration/'
      path: '/track-registration'
      fullPath: '/track-registration/'
      preLoaderRoute: typeof TrackRegistrationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitor-registration/': {
      id: '/visitor-registration/'
      path: '/visitor-registration'
      fullPath: '/visitor-registration/'
      preLoaderRoute: typeof VisitorRegistrationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitor-registration/success/': {
      id: '/visitor-registration/success/'
      path: '/visitor-registration/success'
      fullPath: '/visitor-registration/success/'
      preLoaderRoute: typeof VisitorRegistrationSuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  TrackRegistrationIndexRoute: TrackRegistrationIndexRoute,
  VisitorRegistrationIndexRoute: VisitorRegistrationIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  VisitorRegistrationSuccessIndexRoute: VisitorRegistrationSuccessIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
